version: "3.9"
volumes:
  redis-vol: {}
  mongo-vol: {}
  proxy-tmp-vol:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  mxds-proxy:
    hostname: mxds-proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - proxy-tmp-vol:/run/python/temp
    build:
      context: ../mxds-proxy
      dockerfile: Dockerfile
      args:
        USER_ID: ${CONTAINER_USER_ID:-}

  mxds-web:
    hostname: mxds-web
    build:
      context: ../mxds-web
      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"

